# Generated by Django 2.2.24 on 2021-12-11 08:56

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("authnapp", "0005_create_profiles")]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 12, 13, 8, 56, 37, 509892, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        )
    ]
