# Generated by Django 2.2.24 on 2021-12-11 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("authnapp", "0006_auto_20211211_0856")]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 12, 13, 14, 24, 47, 728346, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        )
    ]
